#!/bin/sh

set -eo pipefail

# absorb brew warnings
status="$(brew services 2>/dev/null | grep yabai | awk '{print $2}')"

if [ "$status" = 'started' ];then
  brew services restart yabai
else
  brew services start yabai
fi
