#!/usr/bin/env sh

# bsp or float (default: bsp)
# yabai -m config layout bsp

# float settings
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Cisco" sticky=on layer=above manage=off
yabai -m rule --add app="^Zoom$" sticky=on layer=above manage=on

yabai -m config window_placement             second_child

yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config window_shadow        on

yabai -m config window_border                on
yabai -m config active_window_border_color   0xAAC8C700
yabai -m config normal_window_border_color   0x00FFFFFF

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# Set all padding and gaps to 12pt (default: 0)
yabai -m config layout bsp
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   10

killall limelight &> /dev/null
limelight &> /dev/null &

echo "yabai configuration loaded.."
